export default () => ({
  availableDownloadDropdownBtnIsOpen: {
    backgroundColor: '#F2F2F2',
    borderTop: '1px solid #155F97',
    borderRight: '1px solid #155F97',
    borderLeft: '1px solid #155F97',
    borderTopRightRadius: '8px',
    borderTopLeftRadius: '8px',
    borderBottomRightRadius: '0px',
    width: '240px',
    borderBottomLeftRadius: '0px',
    boxShadow: 'none',
    '&:hover': {
      backgroundColor: '#F2F2F2',
      boxShadow: 'none',
    },
  },
  availableDownloadDropdownBtn: {
    backgroundColor: '#F2F2F2',
    border: '1px solid #155F97',
    borderRadius: '8px',
    boxShadow: 'none',
    width: '240px',
    textWrap: 'nowrap',
    '&:hover': {
      backgroundColor: '#F2F2F2',
      boxShadow: 'none',
    },
  },
  availableDownloadDropdownBtnLabel: {
    color: '#1D79A8',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    fontFamily: 'Lato',
    textTransform: 'capitalize',
    paddingRight: '6px',
  },
  availableDownloadBtn: {
    backgroundColor: '#155F97 !important',
    boxShadow: 'none',
    '&:hover': {
      boxShadow: 'none',
    },
  },
  availableDownloadDropdownBtnStartIcon: {
    margin: '0px',
  },
  dropdownMenuList: {
    paddingTop: '0px',
    paddingBottom: '0px',
    backgroundColor: '#0d71a3',
    color: 'white',
    borderBottomRightRadius: '8px',
    borderBottomLeftRadius: '8px',
  },
  dropdownPaper: {
    maxWidth: '240px',
    borderBottomRightRadius: '8px',
    borderBottomLeftRadius: '8px',
  },
  downloadFileManifestBtn: {
    backgroundColor: '#1A8CCB',
    borderRadius: '8px',
    border: '1px solid #1A8CCB',
    boxShadow: 'none',
    width: '240px',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    // maxWidth: '287px',
    fontWeight: 400,
    fontSize: '16px',
    textTransform: 'none',
    color: '#fff',
    '&:hover': {
      backgroundColor: '#1A8CCB',
      boxShadow: 'none',
    },
  },
  downloadFileIcon: {
    width: '20px',
    height: '20px',
    verticalAlign: 'middle',
    margingLeft: '4px',
  },
});