export default () => ({
  bodyWrapper: {
    borderBottomLeftRadius: '20px',
    borderBottomRightRadius: '20px',
    borderTopLeftRadius: '20px',
    borderTopRightRadius: '20px',
    margin: '-35px 27px 30px 27px',
    paddingBottom: '30px',
  },
  tableWrapper: {
    margin: '0 30px',
  },
  customFooterStyle: {
    background: '#f3f3f4',
  },
  container_footer: {
    background: 'red',
  },
  jBrowseBtnContainer: {
    marginLeft: '29px',
    marginRight: '29px',
    marginBottom: '8px',
    boxShadow: 'none',
  },
  jBrowseBtn: {
    marginLeft: '27px',
  },
  tableTitleWizard: {
    width: '400px',
    float: 'right',
    paddingTop: '8px',
  },
  link: {
    color: '#dc762f',
    fontWeight: 'bolder',
    '&:hover': {
      color: '#dc762f',
    },
  },
  topButtonGroup: {
    textAlign: 'right',
    padding: '10px 43px 15px 0px',
    position: 'relative',
  },
  messageTopOne: {
    position: 'absolute',
    left: '360px',
    top: '-125px',
    zIndex: '400',
  },
  messageTopTwo: {
    position: 'absolute',
    left: '5px',
    top: '-140px',
    zIndex: '400',
  },
  manifestButtonGroup: {
    marginTop: '10px',
    float: 'right',
  },
  popUpWindowText: {
    fontFamily: 'Lato',
    size: '16px',
  },
  tableDeleteButton: {
    background: '#fff',
    border: '1px solid #ccc',
    width: '29px',
    cursor: 'pointer',
    height: '26px',
    borderRadius: '15%',
    padding: '0',
  },
  tableDeleteButtonDiv: {
    textAlign: 'center',
  },
  removeCell: {
    cursor: 'pointer',
    display: 'inline-flex',
    outline: 'none',
  },
  removeThCell: {
    top: '0px',
    color: '#A61401',
    zIndex: '100',
    position: 'relative',
    fontSize: '11pt',
    borderTop: '#024466 3px solid',
    fontStyle: 'normal',
    fontFamily: "'Lato Regular','Raleway', sans-serif",
    fontWeight: 'bold',
    paddingRight: '-15px',
    borderBottom: '#024466 3px solid',
    letterSpacing: '0.06em',
    backgroundColor: '#F5F5F5',
    width: '120px',
    textAlign: 'center',
  },
  removeHeadCell: {
    display: 'flex',
  },
  removeHeadCellText: {
    lineHeight: '37px',
    position: 'relative',
    left: '15px',
  },
  removeHeadCellIcon: {
    marginTop: '1px',
    verticalAlign: 'top',
    left: '15px',
    position: 'relative',
  },
  removeHeadCellIconButton: {
    color: '#A61401',
    width: '25px',
    marginTop: '5px',
    height: '25px',
  },
  helpIcon: {
    position: 'relative',
    bottom: '8px',
    left: '4px',
    width: '17px',
  },
  removeAllMessage: {
    fontWeight: '500',
    position: 'absolute',
    top: '36px',
    right: '0',
    zIndex: '400',
    background: '#fff',
    border: '2px solid #A61401',
    borderRadius: '7px',
    fontSize: '12px',
    width: '110px',
    height: '48px',
    padding: '5px 0px',
  },
  bottomDivider: {
    marginTop: '22px',
    marginBottom: '40px',
    height: '3px',
    background: '#CFCFCF',
  },
  message: {
    color: '#000000',
    fontSize: '15px',
    fontFamily: '"Open Sans", sans-serif',
    lineHeight: '22px',
    width: '35%',
    marginBottom: '5px',
    paddingLeft: '7px',
  },
  paddingLeftRight: {
    paddingLeft: '30px',
    paddingRight: '30px',
  },
  buttonGroup: {
    position: 'relative',
    paddingBottom: '10px',
  },
  paddingBottom28: {
    paddingBottom: '28px',
  },
  marginTopNegative20: {
    marginTop: '-38px',
  },
  helpBtn: {
    padding: '0px',
  },
  removeBtn: {
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '12px',
    background: '#FFF',
    border: '1px solid #003559',
    borderRadius: '8px',
    color: '#13344A',
    height: '38px',
    width: '95px',
  },
  headerGrid: {
    paddingLeft: '40px',
    paddingRight: '40px',
    paddingTop: '35px',
  },
});
