title: Bento Documentation
description: Documentation for Bento
remote_theme: rundocs/jekyll-rtd-theme

copyright:
  revision: true

edit: true
addons_branch: true

addons:
  - github
  - plugins

  
readme_index:
  with_frontmatter: true  
  
sass:
  style: compressed

## Theme settings for carlosperate/jekyll-theme-rtd
#repo_url: 'https://github.com/CBIIT/bento-docs'
#edit_on_github: true
#github_docs_folder: false
#sticky_navigation: true
#prev_next_buttons_location: both
#search_enabled: true
#hljs_style: github-gist
