const styles = () => ({
  /* Custom Styling by Project */
  localFind: {
    color: '#ff7f15',
  },
});

export const customStyles = {
  clearQueryButton: {
    margin: '1px',
    minWidth: '53px',
    marginLeft: 0,
    fontWeight: 600,
    maxWidth: '53px',
    fontSize: '12px',
    padding: '2px 7px 2px 7px',
    cursor: 'pointer',
    color: '#fff',
    fontFamily: 'Nunito',
    lineHeight: '16px',
    height: '20px',
    borderRadius: '5px',
    textTransform: 'uppercase',
    boxSizing: 'border-box',
    backgroundColor: '#646464',
    border: '1px solid #B4B4B4',
    '&:hover': {
      backgroundColor: '#646464',
    },
  },
  filterCheckboxes: {
    padding: '1px 2px 1px 6px',
    marginRight: 5,
    borderRadius: 5,
    fontSize: 12,
    border: '0.5px solid #646464',
    width: 'fit-content',
    backgroundColor: '#fff',
    cursor: 'pointer',
    color: '#80430A',
    fontFamily: 'Nunito',
    fontWeight: '500',
    lineHeight: '16px',
    letterSpacing: '0em',
    '&:after': {
      content: '" "',
    },
  },
  queryWrapper: {
    minHeight: '77px',
    maxHeight: '125px',
    backgroundColor: '#F3F8FB',
    padding: '8px 17px 12px 17px',
    overflowY: 'auto',
    border: '1px solid #d4d6d7',
  },
  queryContainer: {
    marginLeft: '13px',
    position: 'relative',
    lineHeight: '28px',
    letterSpacing: '0.5px',
    fontFamily: 'Nunito',
    fontSize: '14px',
  },
  filterName: {
    textTransform: 'uppercase',
    padding: '2px 6px 1px 7px',
    borderRadius: '5px',
    fontSize: 12,
    height: '20px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  bracketsOpen: {
    fontSize: 18,
    fontFamily: 'Nunito Sans',
    color: '#787878',
    marginRight: 3,
    fontWeight: 600,
  },
  bracketsClose: {
    fontSize: 18,
    fontFamily: 'Nunito Sans',
    color: '#787878',
    marginLeft: 3,
    fontWeight: 600,
  },
  operators: {
    color: '#646464',
    marginLeft: '3px',
    marginRight: '3px',
    borderBottom: 'none',
    textDecoration: 'none',
    fontSize: 10,
    fontWeight: 'bold',
  },
  localFind: {
    color: '#80430A',
  },
  // localFindBackground: {
  //   color: '#000',
  //   padding: '2px 5px 2px 5px',
  //   borderRadius: '5px',
  //   border: '0.5px solid #646464',
  //   backgroundColor: '#fdf3eb',
  //   fontFamily: 'Nunito',
  //   fontSize: '12px',
  //   fontWeight: '600',
  //   lineHeight: '16px',
  //   letterSpacing: '0em',
  // },
  divider: {
    borderRight: '1px solid #969696',
    marginRight: 0,
    marginLeft: 7,
    height: 26,
    top: 24,
    position: 'absolute',
  },
  localFindBackground: {
    color: '#000',
    borderRadius: '5px',
    // backgroundColor: '#FFB170',
  },
  standAloneInputSet: {
    color: '#80430A',
  },
  facetSectionCases: {
    color: '#80430A',
  },
  facetSectionFilterByCases: {
    color: '#80430A',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#FFFFFF',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '16px',
    letterSpacing: '0em',
    whiteSpace: 'nowrap',
    marginLeft: '1px',
  },
  facetSectionFilterByCasesBackground: {
    color: '#000000',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#fdf3eb',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '600',
    lineHeight: '16px',
    letterSpacing: '0em',
    whiteSpace: 'nowrap',
  },
  facetSectionFilterBySamples: {
    color: '#1F536A',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#FFFFFF',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '16px',
    letterSpacing: '0em',
    whiteSpace: 'nowrap',
  },
  facetSectionFilterBySamplesBackground: {
    color: '#000000',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#E5F2FA',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '600',
    lineHeight: '16px',
    letterSpacing: '0em',
    whiteSpace: 'nowrap',
  },
  facetSectionFilterByFiles: {
    color: '#353F47',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#FFFFFF',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '16px',
    whiteSpace: 'nowrap',
    letterSpacing: '0em',
  },
  facetSectionFilterByFilesBackground: {
    color: '#000000',
    padding: '2px 5px 2px 5px',
    borderRadius: '5px',
    border: '0.5px solid #646464',
    backgroundColor: '#EAECED',
    fontFamily: 'Nunito',
    fontSize: '12px',
    fontWeight: '600',
    lineHeight: '16px',
    letterSpacing: '0em',
    whiteSpace: 'nowrap',
  },
  urlContainer: {
    display: 'flex',
    marginTop: 6,
    minHeight: '10px',
  },
};

export default styles;